"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { launchRegions, type LaunchRegion, type LaunchMembership, type Campaign } from "@/lib/launch-types";
import styles from "./Marketing.module.css";

export default function EarlyAccessForm({ signedIn, campaign }: { signedIn:boolean; campaign:Campaign|null }) {
  const router=useRouter();
  const [region,setRegion]=useState<LaunchRegion>("ROW"), [accepted,setAccepted]=useState(false), [state,setState]=useState<LaunchMembership|null>(null);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/launch/membership",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error || "Membership could not be loaded.");setState(data);}catch(e){setError(e instanceof Error?e.message:"Membership could not be loaded.");}finally{setLoading(false);}}
  useEffect(()=>{const remembered=document.cookie.split("; ").find(row=>row.startsWith("fh_region="))?.split("=")[1];if(launchRegions.some(r=>r.value===remembered))setRegion(remembered as LaunchRegion);if(signedIn)void load();else setLoading(false);},[signedIn]);
  async function join(event:React.FormEvent){event.preventDefault();if(!accepted||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/launch/membership",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({region,accept_terms:accepted})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Your place could not be confirmed. Please try again.");setState(data);router.refresh();window.dispatchEvent(new Event("disclosure-campaign-changed"));}catch(e){setError(e instanceof Error?e.message:"Your place could not be confirmed. Please try again.");}finally{setBusy(false);}}
  const regionSelect=<label>Your region<select value={region} onChange={e=>setRegion(e.target.value as LaunchRegion)} disabled={busy}>{launchRegions.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label>;
  if(!signedIn && campaign?.state==="closed")return <div className={styles.form}><h2>Reservations have closed.</h2><p>The founding-member reservation period has ended. You can contact us to discuss access.</p><Link href="/demo" className="btn">Request a demo</Link><Link href="/signin?next=%2Fearly-access" className="text-link">Already reserved? Sign in to view your membership →</Link></div>;
  const ended=state?.entitlement.phase === "expired";
  if(!signedIn)return <div className={styles.form}><h2>{campaign?.state==="full"?"Join the waiting list.":"Start with your account."}</h2><p>{campaign?.state==="full"?"The twenty founding places are allocated. Verify your email, then return here to join the waiting list. A free place is not guaranteed.":"Verify your email, then return here to confirm your founding membership. Signing in alone does not reserve a place."}</p>{regionSelect}<Link className="btn" href={`/signin?next=%2Fearly-access&region=${region}`}>Verify email and continue →</Link><p className={styles.note}>New to Disclosure? Email sign-in can create your account. All regions currently use Disclosure Global.</p></div>;
  if(loading)return <p role="status">Checking your membership…</p>;
  if(state?.membership)return <div className={styles.success} role="status"><p className="eyebrow">Founding group</p><h2>{state.membership.status==="reserved"?(ended?"Your founding-member access has ended.":state.entitlement.active?"Your launch access is active.":"Your place is reserved."):"You’re on the waiting list."}</h2><p>{state.membership.status==="reserved"?"Your individual account has one of the twenty founding-member places. Launch-plan access runs from 1 November 2026 through 30 April 2027. No payment details or automatic charge.":"The twenty founding-member places are allocated. Joining the waiting list does not guarantee a free place; we’ll contact you if access becomes available."}</p><p className={styles.note}>Region: {launchRegions.find(r=>r.value===state.membership?.region)?.label}. Membership belongs to your account across all regions.</p><Link href="/platform" className="text-link">Explore what’s included →</Link></div>;
  return <form className={styles.form} onSubmit={join}><h2>{state?.campaign.state==="full"?"Join the waiting list.":"Confirm your founding membership."}</h2><p>Your email is verified. Your place is confirmed only when this request succeeds.</p>{regionSelect}<p className={styles.note}>All regions use Disclosure Global. Region does not change document coverage or data hosting.</p>
    {state?.campaign.state==="closed"?<p>The founding-member reservation period has ended. <Link href="/demo">Request a demo</Link> to discuss access.</p>:<><label className={styles.check}><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} disabled={busy}/><span>I have read the <a href="#offer-terms">founding-member offer</a> and understand this is one individual account, with AI subject to available service limits.</span></label><button className="btn" disabled={!state||!accepted||busy} type="submit">{busy?"Confirming…":state?.campaign.state==="full"?"Join waiting list":"Reserve my founding place"}</button></>}
    {error&&<p className={styles.error} role="alert">{error}</p>}{!state&&<button className="btn secondary" type="button" onClick={()=>void load()}>Retry membership check</button>}
  </form>;
}
