import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import { chromium } from "playwright";

const base = process.env.ADMIN_SMOKE_BASE_URL || "http://localhost:3201";
const artifacts = path.resolve(process.env.ADMIN_SMOKE_ARTIFACT_DIR || ".browser-results/admin");
const mutationReason = `Synthetic browser suspension verification ${Date.now()}`;
const replacement = process.env.ADMIN_SMOKE_PASSWORD || "Synthetic operator phrase! 9876";
await mkdir(artifacts, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.SMOKE_CHANNEL ? { channel: process.env.SMOKE_CHANNEL } : {}) });
const operator = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const ordinary = await browser.newContext();
const page = await operator.newPage();
const analyst = await ordinary.newPage();
page.setDefaultTimeout(20000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
async function check(name, fn) { await fn(); console.log("PASS " + name); }
async function navigate(name) { await page.getByRole("navigation", { name: "Administration sections" }).getByRole("button", { name, exact: true }).click(); await page.getByRole("heading", { name, exact: true, level: 1 }).waitFor(); }
async function review(reason) {
  const modal = page.getByRole("dialog");
  await modal.getByLabel("Operational reason").fill(reason);
  await modal.getByLabel("Re-enter administrator password").fill(replacement);
  await modal.getByRole("checkbox").check();
  await modal.getByRole("button", { name: "Confirm reviewed change" }).click();
}
try {
  await check("Ordinary account and forged headers cannot access control plane", async () => {
    await analyst.goto(base + "/signin");
    await analyst.locator("input[type=email]").fill("analyst-admin-smoke@example.test");
    await analyst.getByRole("button", { name: "Email me a link" }).click();
    await analyst.getByRole("link", { name: "open the link" }).click();
    await analyst.waitForURL(base + "/");
    assert.equal((await ordinary.request.get(base + "/api/platform-admin/users", { headers: { "X-Admin-Session": "disclosure.forged", "X-Role": "superadmin" } })).status(), 401);
    for (const route of ["demo-requests", "launch-memberships"]) assert.equal((await ordinary.request.get(base + "/api/platform-admin/" + route)).status(), 401);
    assert.equal((await ordinary.request.post(base + "/api/platform-admin/login", { headers: { Origin: "https://attacker.example" }, data: { username: "disclosure", password: "1234" } })).status(), 403);
    assert.equal((await ordinary.request.get(base + "/api/sessions")).status(), 200);
  });
  await check("Explicit local bootstrap forces a strong change and keeps tokens HttpOnly", async () => {
    await page.goto(base + "/admin");
    await page.getByLabel("Administrator password", { exact: true }).fill("1234");
    const loginResponse = page.waitForResponse(response => response.url().endsWith("/api/platform-admin/login"));
    await page.getByRole("button", { name: "Sign in to administration" }).click();
    assert.equal((await (await loginResponse).json()).token, undefined);
    await page.getByRole("heading", { name: "Choose your own password." }).waitFor();
    assert.equal((await operator.request.get(base + "/api/platform-admin/users")).status(), 403);
    await page.getByLabel("Initial or current password").fill("1234");
    await page.getByLabel("New password", { exact: true }).fill(replacement);
    await page.getByLabel("Repeat new password").fill(replacement);
    await page.getByRole("button", { name: "Change password and continue" }).click();
    await page.getByRole("heading", { name: "Overview", exact: true, level: 1 }).waitFor();
    await page.getByText("Synthetic", { exact: true }).count();
    const cookie = (await operator.cookies()).find(row => row.name === "disclosure_admin_dev");
    assert.ok(cookie?.httpOnly && cookie.sameSite === "Strict");
    assert.ok(!(await page.evaluate(() => document.cookie)).includes("disclosure_admin_dev"));
    await page.getByRole("heading", { name: "Recent ingestion runs" }).waitFor();
    await page.screenshot({ path: path.join(artifacts, "admin-overview.png"), fullPage: true });
  });
  await check("Enquiries preserve submitted details and reviewed status changes with an audit", async () => {
    const reference = randomUUID();
    const workflow = `Synthetic demo enquiry ${reference}: compare filings across reporting periods.`;
    const sent = await ordinary.request.post(base + "/api/demo-requests", { headers: { Origin: base }, data: {
      request_id: reference, name: "Synthetic Enquiry Analyst", email: `demo-${reference}@example.test`,
      organisation: "Synthetic Research", region: "ROW", workflow,
    } });
    assert.equal(sent.status(), 201, await sent.text());
    assert.deepEqual(await sent.json(), { received: true, reference });
    assert.equal((await ordinary.request.post(base + `/api/platform-admin/demo-requests/${reference}/status`, { headers: { Origin: base }, data: { status: "completed" } })).status(), 401);
    await navigate("Enquiries");
    await page.getByLabel("Search Enquiries").fill(reference);
    await page.getByRole("button", { name: "Search", exact: true }).click();
    const enquiry = page.getByRole("row").filter({ hasText: `demo-${reference}@example.test` });
    await enquiry.getByText("new", { exact: true }).waitFor();
    await enquiry.getByText("Read enquiry", { exact: true }).click();
    await enquiry.getByText(workflow, { exact: true }).waitFor();
    await enquiry.getByLabel(`Change enquiry status for demo-${reference}@example.test`).selectOption("contacted");
    const reason = `Synthetic enquiry review ${reference}`;
    await review(reason);
    await page.getByRole("dialog").waitFor({ state: "hidden" });
    await page.getByRole("status").filter({ hasText: "Update enquiry status completed" }).waitFor();
    const saved = await operator.request.get(base + `/api/platform-admin/demo-requests?q=${reference}`);
    assert.equal(saved.status(), 200);
    const records = (await saved.json()).items;
    assert.equal(records.length, 1);
    assert.equal(records[0].status, "contacted");
    assert.equal(records[0].revision, 2);
    assert.equal(records[0].workflow, workflow);
    assert.equal(records[0].caller_hash, undefined);
    const audit = (await (await operator.request.get(base + `/api/platform-admin/audit?q=${reference}`)).json()).items;
    assert.ok(audit.some(row => row.action === "demo.status" && row.metadata.reason === reason && row.metadata.status === "contacted"));
    await page.reload();
    await page.getByRole("heading", { name: "Overview", exact: true, level: 1 }).waitFor();
    await navigate("Enquiries");
    await page.getByLabel("Filter by status").selectOption("contacted");
    await page.getByLabel("Search Enquiries").fill(reference);
    await page.getByRole("button", { name: "Search", exact: true }).click();
    await page.getByRole("row").filter({ hasText: `demo-${reference}@example.test` }).getByText("contacted", { exact: true }).waitFor();
    await page.screenshot({ path: path.join(artifacts, "admin-enquiries.png"), fullPage: true });
  });
  await check("Founding group shows durable individual reservations without allocation controls", async () => {
    const joined = await ordinary.request.post(base + "/api/launch/membership", { headers: { Origin: base }, data: { region: "EU", accept_terms: true } });
    assert.equal(joined.status(), 200, await joined.text());
    const first = await joined.json();
    assert.equal(first.membership.status, "reserved");
    assert.equal(first.entitlement.active, false);
    const repeated = await ordinary.request.post(base + "/api/launch/membership", { headers: { Origin: base }, data: { region: "ROW", accept_terms: true } });
    assert.equal(repeated.status(), 200);
    assert.deepEqual((await repeated.json()).membership, first.membership);
    assert.equal((await repeated.json()).campaign.allocated, first.campaign.allocated);
    await navigate("Founding group");
    await page.getByLabel("Search Founding group").fill("analyst-admin-smoke@example.test");
    await page.getByRole("button", { name: "Search", exact: true }).click();
    const row = page.getByRole("row").filter({ hasText: "analyst-admin-smoke@example.test" });
    await row.getByText("reserved", { exact: true }).waitFor();
    await row.getByText("EU", { exact: true }).waitFor();
    assert.equal(await row.getByRole("button").count(), 0);
    assert.equal(await row.getByRole("combobox").count(), 0);
    const roster = await operator.request.get(base + "/api/platform-admin/launch-memberships?q=analyst-admin-smoke@example.test&status=reserved&limit=1");
    assert.equal(roster.status(), 200);
    const record = await roster.json();
    assert.equal(record.total, 1);
    assert.equal(record.items[0].region, "EU");
    assert.equal(record.items[0].benefit_starts_at, "2026-11-01T00:00:00+00:00");
    assert.equal(record.items[0].benefit_ends_at, "2027-05-01T00:00:00+00:00");
    assert.equal(record.campaign.capacity, 20);
    assert.equal((await operator.request.post(base + "/api/platform-admin/launch-memberships", { headers: { Origin: base }, data: {} })).status(), 404);
    await page.screenshot({ path: path.join(artifacts, "admin-founding-group.png"), fullPage: true });
  });
  let uid;
  await check("Reviewed suspension handles failure and then revokes real user access", async () => {
    await navigate("Accounts");
    await page.getByLabel("Search Accounts").fill("analyst-admin-smoke");
    await page.getByRole("button", { name: "Search", exact: true }).click();
    await page.getByRole("button", { name: "analyst-admin-smoke@example.test", exact: true }).click();
    const account = page.getByRole("article", { name: "Account details" });
    await account.getByRole("button", { name: "Review suspension" }).click();
    const statusRoute = /\/api\/platform-admin\/users\/[a-z0-9]+\/status$/;
    await page.route(statusRoute, route => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Simulated storage failure; no status change." }) }));
    await review(mutationReason);
    await page.getByRole("dialog").getByRole("alert").filter({ hasText: "Simulated storage failure" }).waitFor();
    assert.equal((await ordinary.request.get(base + "/api/sessions")).status(), 200);
    await page.unroute(statusRoute);
    await review(mutationReason);
    await page.getByRole("dialog").waitFor({ state: "hidden" });
    await page.getByRole("status").filter({ hasText: "Suspend account completed" }).waitFor();
    const response = await operator.request.get(base + "/api/platform-admin/users?q=analyst-admin-smoke");
    const user = (await response.json()).items[0];
    uid = user.id;
    assert.equal(user.status, "suspended");
    assert.equal((await ordinary.request.get(base + "/api/sessions")).status(), 401);
    await account.getByRole("button", { name: "Review account restoration" }).waitFor();
    await page.screenshot({ path: path.join(artifacts, "admin-account-suspended.png"), fullPage: true });
  });
  await check("Backend audit records the actual reviewed mutation", async () => {
    await navigate("Audit history");
    await page.getByLabel("Search Audit history").fill(uid);
    await page.getByRole("button", { name: "Search", exact: true }).click();
    const auditRow = page.getByRole("row").filter({ hasText: mutationReason });
    await auditRow.getByText("account.status", { exact: true }).waitFor();
    await auditRow.getByText(mutationReason, { exact: true }).click();
    assert.match(await auditRow.locator("pre").innerText(), /"status": "suspended"/);
    assert.ok(!(await page.locator("body").innerText()).includes(replacement));
    await page.screenshot({ path: path.join(artifacts, "admin-audit.png"), fullPage: true });
  });
  await check("Source and incomplete coverage states remain honest; mobile stays usable", async () => {
    await navigate("Source readiness");
    await page.getByRole("heading", { name: "Broker and independent research", exact: true }).waitFor();
    assert.ok((await page.getByText("provider required", { exact: true }).count()) > 0);
    await navigate("Research index");
    await page.getByRole("heading", { name: "Incomplete filing inventories", exact: true }).waitFor();
    await navigate("Research jobs");
    await page.getByRole("heading", { name: "Durable research jobs" }).waitFor();
    await page.getByText("Scheduling state: not activated", { exact: true }).waitFor();
    const jobs = await (await operator.request.get(base + "/api/platform-admin/jobs")).json();
    assert.equal(jobs.state, "available");
    assert.ok((jobs.jobs || []).every(job => !Object.hasOwn(job, "token") && !Object.hasOwn(job, "idempotency_key")));
    await page.setViewportSize({ width: 390, height: 844 });
    await navigate("Accounts");
    await page.getByLabel("Search Accounts").waitFor();
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
    await page.screenshot({ path: path.join(artifacts, "admin-mobile.png"), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
  });
  await check("Failed logout preserves session; successful logout revokes it server-side", async () => {
    await page.route("**/api/platform-admin/logout", route => route.fulfill({ status: 503, contentType: "application/json", body: '{"error":"Simulated logout failure"}' }));
    await page.getByRole("button", { name: "Sign out operator" }).click();
    await page.getByRole("alert").filter({ hasText: "Simulated logout failure" }).waitFor();
    assert.equal((await operator.request.get(base + "/api/platform-admin/session")).status(), 200);
    await page.unroute("**/api/platform-admin/logout");
    await page.getByRole("button", { name: "Sign out operator" }).click();
    await page.getByRole("heading", { name: "Manage the platform." }).waitFor();
    assert.equal((await operator.request.get(base + "/api/platform-admin/session")).status(), 401);
    await page.getByLabel("Administrator password", { exact: true }).fill(replacement);
    await page.getByRole("button", { name: "Sign in to administration" }).click();
    await page.getByRole("heading", { name: "Overview", exact: true, level: 1 }).waitFor();
  });
  assert.deepEqual(errors, []);
} finally { await browser.close(); }
