import assert from "node:assert/strict";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { chromium } from "playwright";
const base=process.env.SMOKE_BASE_URL||"http://localhost:3100",api=process.env.SMOKE_API_BASE_URL||"http://127.0.0.1:8100";
const artifacts=path.resolve(".browser-results/ownership");await mkdir(artifacts,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.SMOKE_CHANNEL?{channel:process.env.SMOKE_CHANNEL}:{})}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.setDefaultTimeout(20000);
const errors=[],scenarios=[];page.on("pageerror",error=>errors.push(error.message));
const section=flow=>page.locator(`#${flow}`),card=(flow,name)=>section(flow).locator("[data-ownership-card]").filter({has:page.getByRole("heading",{name,exact:true})});
async function check(name,action){await action();scenarios.push(name);console.log("PASS "+name);}
async function backend(route){const response=await fetch(api+route,{headers:{"X-API-Key":"preview"}});assert.equal(response.status,200);return response.json();}
try{
 const insiders=await backend("/companies/320193/ownership/insiders?limit=50"),jordanIndex=insiders.items.findIndex(item=>item.name==="Jordan Avery (synthetic)");assert.equal(insiders.total,23);assert.ok(jordanIndex>=0);
 await check("Company overview and ownership route keep three disclosure types distinct",async()=>{
  await page.goto(base+"/companies/320193");await page.getByRole("heading",{name:"Ownership, in context.",exact:true}).waitFor();await page.getByRole("navigation",{name:"Company navigation"}).getByRole("link",{name:"Ownership",exact:true}).click();await page.getByRole("heading",{name:"Who reported what.",exact:true}).waitFor();
  for(const flow of ["insiders","institutions","events"]){await section(flow).locator('[data-ownership-card]').first().waitFor();assert.ok((await section(flow).innerText()).includes("Partial ownership coverage"));}
  assert.equal(await card("institutions","Northstar Research Partners (synthetic)").count(),1);assert.equal(await card("events","Harbor Capital (synthetic)").count(),1);assert.match(await section("events").innerText(),/does not establish activism/);
  await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(artifacts,"ownership-desktop.png"),fullPage:true});
 });
 await check("Independent pagination retains filters and returns every insider exactly once",async()=>{
  await page.goto(base+"/companies/320193/ownership?events_from=2020-01-01");await section("insiders").getByText("20 shown",{exact:false}).waitFor().catch(()=>section("insiders").locator('[data-ownership-card]').first().waitFor());
  const first=await section("insiders").locator('[data-ownership-card] h3').allTextContents();assert.equal(first.length,20);
  const next=page.getByRole("navigation",{name:"Insider activity pages"}).getByRole("link",{name:"Next →",exact:true});await next.focus();await next.press("Enter");await page.waitForURL(url=>url.searchParams.get("insiders_offset")==="20");await page.getByRole("navigation",{name:"Insider activity pages"}).getByText("Page 2",{exact:true}).waitFor();
  const second=await section("insiders").locator('[data-ownership-card] h3').allTextContents();assert.equal(second.length,3);assert.equal(new Set([...first,...second]).size,23);assert.equal(new URL(page.url()).searchParams.get("events_from"),"2020-01-01");
 });
 await check("Compatible insider history and exact source inspection preserve the originating view",async()=>{
  const offset=Math.floor(jordanIndex/20)*20;await page.goto(base+`/companies/320193/ownership?events_from=2020-01-01&insiders_offset=${offset}`);const person=card("insiders","Jordan Avery (synthetic)");await person.waitFor();await person.getByRole("img",{name:/Reported holdings observations/}).waitFor();await person.getByText("View exact observations",{exact:true}).click();assert.match(await person.innerText(),/1,000/);assert.match(await person.innerText(),/1,100/);
  const summary=person.locator("details > summary").filter({hasText:"View filings"});await summary.focus();await summary.press("Enter");await person.getByRole("link",{name:/^4 · Filed/}).first().click();await page.getByRole("region",{name:"Extracted ownership facts",exact:true}).waitFor();assert.match(await page.locator("main").innerText(),/Jordan Avery/);await page.getByText("Inspect captured source text / XML",{exact:true}).click();assert.match(await page.getByLabel("Captured ownership source text",{exact:true}).innerText(),/<ownershipDocument>/);
  await page.getByRole("link",{name:"← Return to the same ownership filters",exact:true}).click();await section("insiders").locator('[data-ownership-card]').first().waitFor();assert.equal(new URL(page.url()).searchParams.get("events_from"),"2020-01-01");assert.equal(Number(new URL(page.url()).searchParams.get("insiders_offset")||0),offset);
 });
 await check("Sales filter and CSV use the same scope; export failures retain the page",async()=>{
  await section("insiders").getByLabel("Transaction filter",{exact:true}).selectOption("sales");await section("insiders").getByRole("button",{name:"Apply insiders filters",exact:true}).click();await page.waitForURL(url=>url.searchParams.get("insiders_direction")==="sales");await card("insiders","Morgan Reed (synthetic)").waitFor();assert.equal(await section("insiders").locator('[data-ownership-card]').count(),1);assert.equal(new URL(page.url()).searchParams.has("insiders_offset"),false);assert.equal(new URL(page.url()).searchParams.get("events_from"),"2020-01-01");
  const original=page.url();await page.route("**/api/ownership/320193/insiders/export?*",route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({error:"Synthetic export outage; filters retained"})}));await section("insiders").getByRole("button",{name:"Export insiders CSV ↓",exact:true}).click();await section("insiders").getByRole("alert").filter({hasText:"Synthetic export outage"}).waitFor();assert.equal(page.url(),original);await page.unroute("**/api/ownership/320193/insiders/export?*");
  const downloadPromise=page.waitForEvent("download");await section("insiders").getByRole("button",{name:"Export insiders CSV ↓",exact:true}).click();const download=await downloadPromise;const csv=await readFile(await download.path(),"utf8");assert.match(csv,/Morgan Reed/);assert.doesNotMatch(csv,/Jordan Avery/);assert.match(download.suggestedFilename(),/insiders\.csv$/);
 });
 await check("Institutional baseline and beneficial events retain their own dates and sources",async()=>{
  const manager=card("institutions","Northstar Research Partners (synthetic)");assert.match(await manager.innerText(),/2026-03-31/);assert.match(await manager.innerText(),/2026-06-30/);assert.match(await manager.innerText(),/8,000/);assert.match(await manager.innerText(),/10,000/);
  const owner=card("events","Harbor Capital (synthetic)");await owner.locator("summary").filter({hasText:"View filings"}).click();await owner.getByRole("link",{name:/SCHEDULE 13D · Filed/}).first().click();await page.getByRole("region",{name:"Extracted ownership facts",exact:true}).waitFor();assert.match(await page.locator("main").innerText(),/037833100/);assert.match(await page.locator("main").innerText(),/no activist conclusion/);
 });
 await check("Watchlist keeps separate ownership feeds and explicit alert selections across reload",async()=>{
  await page.goto(base+"/signin");await page.locator('input[type=email]').fill(`ownership-${Date.now()}@example.test`);await page.getByRole("button",{name:"Email me a link"}).click();await page.getByRole("link",{name:"open the link"}).click();await page.waitForURL(base+"/");await page.goto(base+"/companies/320193");await page.getByRole("button",{name:"Follow company",exact:true}).click();await page.getByRole("button",{name:"Following",exact:true}).waitFor();await page.goto(base+"/watchlist");
  for(const name of ["Recent insider activity","Recent institutional positions","Recent beneficial ownership"]){const group=page.getByRole("region",{name,exact:true});await group.locator('[data-ownership-card]').first().waitFor();}
  const alerts=page.getByRole("group",{name:"Optional ownership alerts",exact:true});await alerts.getByLabel("Insider activity",{exact:true}).check();await alerts.getByLabel("Beneficial ownership",{exact:true}).check();await page.getByRole("button",{name:"Enable email alerts",exact:true}).click();await page.getByRole("status").filter({hasText:"Alerts are enabled for this list"}).waitFor();const persisted=await(await context.request.get(base+"/api/subscribe")).json();assert.deepEqual([...persisted.ownership_flows].sort(),["events","insiders"]);await page.reload();await page.getByRole("button",{name:"Update alert companies",exact:true}).waitFor();assert.equal(await alerts.getByLabel("Insider activity",{exact:true}).isChecked(),true);assert.equal(await alerts.getByLabel("Institutional positions",{exact:true}).isChecked(),false);
 });
 await check("Mobile ownership retains keyboard source controls without horizontal overflow",async()=>{
  await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:"reduce"});await page.goto(base+"/companies/320193/ownership?insiders_direction=sales");await card("insiders","Morgan Reed (synthetic)").waitFor();const summary=card("insiders","Morgan Reed (synthetic)").locator("summary").filter({hasText:"View filings"});await summary.focus();await summary.press("Enter");assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(artifacts,"ownership-mobile.png"),fullPage:true});assert.deepEqual(errors,[]);
 });
 await writeFile(path.join(artifacts,"acceptance.json"),JSON.stringify({passed:scenarios.length,scenarios,runtimeErrors:errors},null,2));
}catch(error){await page.screenshot({path:path.join(artifacts,"failure.png"),fullPage:true}).catch(()=>{});console.error("FAILED AT",page.url());throw error;}finally{await browser.close();}
