import assert from "node:assert/strict";
import { mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import { chromium } from "playwright";

const base = process.env.SMOKE_BASE_URL || "http://localhost:3100";
const artifacts = path.resolve(process.env.SMOKE_ARTIFACT_DIR || ".browser-results/platform");
await mkdir(artifacts, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.SMOKE_CHANNEL ? { channel: process.env.SMOKE_CHANNEL } : {}) });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const second = await browser.newContext();
const page = await context.newPage();
const secondPage = await second.newPage();
page.setDefaultTimeout(15000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
async function check(name, action) { await action(); console.log("PASS " + name); }
async function visit(route) { await page.goto(base + route); await page.locator("main h1").first().waitFor(); }
async function signIn(target, email) {
  await target.goto(base + "/signin");
  await target.locator("input[type=email]").fill(email);
  await target.getByRole("button", { name: "Email me a link" }).click();
  await target.getByRole("link", { name: "open the link" }).click();
  await target.waitForURL(base + "/");
}
let projectId;
let sourcePath;
try {
  await check("Indexed search, invalid query, source version and company filter", async () => {
    await visit("/research");
    await page.getByRole("region", { name: "Search index coverage" }).waitFor();
    await page.locator("#site-search").fill('"share repurchase"');
    await page.getByRole("button", { name: "Search filings", exact: true }).click();
    await page.locator(".research-results li").first().waitFor();
    assert.match(await page.locator(".result-snippet").first().innerText(), /repurchase/i);
    await page.getByRole("button", { name: "Inspect source", exact: true }).first().click();
    await page.getByRole("complementary", { name: "Selected search result evidence" }).waitFor();
    sourcePath = await page.locator("#research-evidence").getByRole("link", { name: "Read this indexed version" }).getAttribute("href");
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: path.join(artifacts,"research-evidence.png"),fullPage:true });
    await page.locator("#research-evidence").getByRole("link", { name: "Read this indexed version" }).click();
    await page.getByRole("region", { name: "Extracted filing text" }).waitFor();
    assert.match(await page.locator(".indexed-text").innerText(),/repurchase/i);
    await visit('/research?q=%22unclosed');
    await page.getByRole("heading", {name:"Check your search"}).waitFor();
    assert.equal(await page.locator("#site-search").inputValue(),'"unclosed');
    await visit("/research");
    await page.locator("#research-company").fill("AAPL");
    await page.getByRole("option").filter({hasText:"Apple"}).waitFor();
    await page.locator("#research-company").press("ArrowDown");
    await page.locator("#research-company").press("Enter");
    await page.locator("#site-search").fill("repurchase");
    await page.getByRole("button",{name:"Search filings",exact:true}).click();
    await page.locator(".research-results li").first().waitFor();
    assert.equal(new URL(page.url()).searchParams.get("cik"),"320193");
    assert.ok((await page.locator(".result-meta a").allTextContents()).every(name => /Apple/i.test(name)));
  });
  const email = `platform-${Date.now()}@example.com`;
  await check("Session list, failed revoke and server-enforced revoke of another browser", async () => {
    await signIn(page,email); await signIn(secondPage,email);
    await visit("/settings/security");
    assert.equal(await page.locator(".session-list > li").count(),2);
    await page.route("**/api/sessions?*",route => route.request().method() === "DELETE" ? route.fulfill({status:503,contentType:"application/json",body:'{"error":"Simulated revoke failure"}'}) : route.continue());
    await page.getByRole("button",{name:"Sign out session",exact:true}).click();
    await page.getByRole("alert").filter({hasText:"Simulated revoke failure"}).waitFor();
    assert.equal(await page.locator(".session-list > li").count(),2);
    await page.unroute("**/api/sessions?*");
    await page.getByRole("button",{name:"Sign out other sessions",exact:true}).click();
    await page.getByRole("button",{name:"Sign out 1 other session",exact:true}).click();
    await page.getByRole("status").filter({hasText:"1 other session signed out"}).waitFor();
    assert.equal((await second.request.get(base + "/api/sessions")).status(),401);
    assert.equal(await page.locator(".session-list > li").count(),1);
  });
  await check("Project creation, persistent thesis and draft-safe revision conflict", async () => {
    await visit("/projects");
    await page.getByRole("button",{name:"New project",exact:true}).click();
    await page.getByRole("textbox",{name:"Project name",exact:true}).fill("Browser acceptance project");
    await page.getByRole("button",{name:"Create project",exact:true}).click();
    await page.waitForURL(/\/projects\/[a-z0-9]+$/);
    projectId = new URL(page.url()).pathname.split("/").pop();
    await page.getByRole("textbox",{name:"Note title",exact:true}).fill("Repurchase thesis");
    await page.getByRole("combobox",{name:"Note type",exact:true}).selectOption("thesis");
    await page.getByRole("textbox",{name:"Your analysis",exact:true}).fill("My original research draft.");
    await page.getByRole("button",{name:"Save note",exact:true}).click();
    await page.getByRole("status").filter({hasText:"Saved to this project"}).waitFor();
    await page.reload();
    assert.equal(await page.getByRole("textbox",{name:"Your analysis",exact:true}).inputValue(),"My original research draft.");
    const note = (await (await context.request.get(base+`/api/projects/${projectId}/notes`)).json()).notes[0];
    await page.getByRole("textbox",{name:"Your analysis",exact:true}).fill("My unsaved local revision.");
    const remote = await context.request.patch(base+`/api/projects/${projectId}/notes/${note.id}`,{data:{expected_revision:note.revision,body:"Another session changed this note."}});
    assert.equal(remote.status(),200);
    await page.getByRole("button",{name:"Save changes",exact:true}).click();
    await page.getByRole("alert").filter({hasText:"changed in another session"}).waitFor();
    assert.equal(await page.getByRole("textbox",{name:"Your analysis",exact:true}).inputValue(),"My unsaved local revision.");
    await page.getByRole("button",{name:"Compare latest saved version",exact:true}).click();
    await page.locator(".note-conflict").getByText("Another session changed this note.",{exact:true}).waitFor();
    await page.getByRole("button",{name:"Keep my draft for merging",exact:true}).click();
    await page.getByRole("textbox",{name:"Your analysis",exact:true}).fill("Merged both research observations.");
    await page.getByRole("button",{name:"Save changes",exact:true}).click();
    await page.getByRole("status").filter({hasText:"Saved to this project"}).waitFor();
    await page.reload();
    assert.equal(await page.getByRole("textbox",{name:"Your analysis",exact:true}).inputValue(),"Merged both research observations.");
  });
  await check("Source document to project reference, persistent and resolved", async () => {
    await visit(sourcePath);
    await page.getByRole("button",{name:"Add source to project",exact:true}).click();
    await page.locator(".save-source-panel select").selectOption(projectId);
    await page.getByRole("button",{name:"Save source note",exact:true}).click();
    await page.getByRole("link",{name:"Open project →",exact:true}).click();
    await page.getByText("Source available",{exact:true}).waitFor();
    await page.getByRole("link",{name:"Open indexed source ↗",exact:true}).waitFor();
    await page.screenshot({path:path.join(artifacts,"project-source.png"),fullPage:true});
  });
  await check("Starter templates keep attribution and saved research exports portable JSON", async () => {
    await visit("/projects");
    await page.getByRole("button",{name:"New project",exact:true}).click();
    await page.getByRole("textbox",{name:"Project name",exact:true}).fill("Template acceptance project");
    await page.getByRole("combobox",{name:"Starting point",exact:true}).selectOption("company-overview");
    await page.locator(".template-preview").waitFor();
    await page.getByRole("button",{name:"Create project",exact:true}).click();
    await page.waitForURL(/\/projects\/[a-z0-9]+$/);
    const templateProjectId = new URL(page.url()).pathname.split("/").pop();
    await page.locator(".template-origin").waitFor();
    assert.ok(await page.locator(".project-notes-nav li").count() > 0);
    const savedDownload = page.waitForEvent("download");
    await page.getByRole("button",{name:"Download saved research",exact:true}).click();
    const filename = path.join(artifacts,"template-project.json");
    await (await savedDownload).saveAs(filename);
    const content = await readFile(filename,"utf8");
    const exported = JSON.parse(content);
    assert.equal(exported.format,"disclosure.research-project"); assert.equal(exported.schema_version,1);
    assert.equal(exported.project.id,templateProjectId); assert.equal(exported.scope.kind,"personal");
    assert.ok(exported.notes.every(note => note.authorship === "template"));
    assert.ok(!content.includes(email)); assert.equal(Object.hasOwn(exported,"users"),false); assert.equal(Object.hasOwn(exported,"documents"),false);
    const exportResponse = await context.request.get(base+`/api/projects/${templateProjectId}/export`);
    assert.match(exportResponse.headers()["cache-control"],/no-store/);
    assert.equal((await second.request.get(base+`/api/projects/${templateProjectId}/export`)).status(),401);
    await page.getByRole("textbox",{name:"Note title",exact:true}).fill("My company overview");
    await page.getByRole("textbox",{name:"Your analysis",exact:true}).fill("A user-written observation replacing the starter prompts.");
    await page.getByRole("button",{name:"Save changes",exact:true}).click();
    await page.getByRole("status").filter({hasText:"Saved to this project"}).waitFor();
    assert.equal(await page.locator(".template-origin").count(),0);
    const updated = await (await context.request.get(base+`/api/projects/${templateProjectId}/export`)).json();
    const edited = updated.notes.find(note => note.title === "My company overview");
    assert.equal(edited.authorship,"user"); assert.equal(edited.origin.kind,"starter_template");
    await page.screenshot({path:path.join(artifacts,"project-template.png"),fullPage:true});
  });
  await check("Filing-date cutoff changes the grid and export without entering saved profiles", async () => {
    await visit("/companies/320193/statements?mode=annual");
    await page.getByRole("button",{name:/Display options/}).click();
    await page.getByLabel("Filings available by",{exact:true}).fill("2024-12-31");
    await page.getByRole("button",{name:"Apply cutoff",exact:true}).click();
    await page.waitForURL(url => url.searchParams.get("as_of") === "2024-12-31");
    await page.locator(".cutoff-notice").waitFor();
    const headings = await page.locator(".stmt thead").innerText();
    assert.match(headings,/FY2024/); assert.doesNotMatch(headings,/FY2025/);
    await page.getByRole("button",{name:/Export to Excel/}).click();
    const dialog = page.getByRole("dialog",{name:"Export to Excel"});
    await dialog.getByText(/This workbook includes filings available by 2024-12-31/).waitFor();
    const requestPromise = page.waitForRequest(request => request.url().includes("/api/export?"));
    const downloadPromise = page.waitForEvent("download");
    await dialog.getByRole("button",{name:"Download Excel",exact:true}).click();
    assert.equal(new URL((await requestPromise).url()).searchParams.get("as_of"),"2024-12-31");
    await downloadPromise;
    await dialog.getByRole("textbox",{name:"Export profile name",exact:true}).fill("Cutoff acceptance profile");
    await dialog.getByRole("button",{name:"Save profile",exact:true}).click();
    await dialog.getByRole("status").filter({hasText:'Profile “Cutoff acceptance profile” saved.'}).waitFor();
    const saved = (await (await context.request.get(base+"/api/prefs")).json()).prefs.find(pref => pref.key === "profile" && pref.scope_key === "Cutoff acceptance profile");
    assert.ok(saved); assert.equal(Object.hasOwn(saved.value,"as_of"),false);
    await dialog.getByRole("button",{name:"Close",exact:true}).click();
    await page.locator(".cutoff-notice").getByRole("button",{name:"Clear cutoff",exact:true}).click();
    await page.waitForURL(url => !url.searchParams.has("as_of"));
    await page.getByRole("button",{name:/Export to Excel/}).click();
    const noCutoffRequest = page.waitForRequest(request => request.url().includes("/api/export?"));
    const noCutoffDownload = page.waitForEvent("download");
    await dialog.getByRole("button",{name:"Download Excel",exact:true}).click();
    assert.equal(new URL((await noCutoffRequest).url()).searchParams.has("as_of"),false);
    await noCutoffDownload;
    await dialog.getByRole("button",{name:"Close",exact:true}).click();
  });
  await check("Compact statement settings, keyboard tabs and mobile project width", async () => {
    await visit("/companies/320193/statements");
    assert.equal(await page.locator("#statement-display-options").isVisible(),false);
    await page.getByRole("button",{name:/Display options/}).click();
    await page.getByRole("combobox",{name:"Where Scale preference applies",exact:true}).waitFor();
    const firstTab = page.getByRole("tab").first();
    await firstTab.focus(); await firstTab.press("ArrowRight");
    await page.waitForFunction(() => document.querySelectorAll('[role="tab"]')[1]?.getAttribute("aria-selected") === "true");
    await page.setViewportSize({width:390,height:844});
    for(const route of ["/research?q=repurchase",`/projects/${projectId}`,"/settings/security"]){
      await visit(route);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), route+" fits mobile");
    }
    await page.emulateMedia({reducedMotion:"reduce"});
    await visit("/research?q=repurchase");
    await page.getByRole("button",{name:"Inspect source",exact:true}).first().click();
    assert.ok(await page.locator("#research-evidence").isVisible());
    await page.waitForFunction(() => document.getAnimations().every(animation => animation.playState !== "running"));
    await page.screenshot({path:path.join(artifacts,"research-mobile.png"),fullPage:true});
  });
  await check("Cross-company comparison retains sources and shows unavailable concepts", async () => {
    await page.setViewportSize({width:1440,height:1000});
    await visit("/compare?companies=AAPL,JPM&concept=NetIncomeLoss&period=FY2025");
    await page.getByRole("link",{name:"View filing →",exact:true}).first().waitFor();
    assert.equal(await page.getByRole("link",{name:"View filing →",exact:true}).count(),2);
    assert.match(await page.locator("main").innerText(),/2025/);
    await visit("/compare?companies=AAPL,JPM&concept=DoesNotExist&period=FY2025");
    await page.getByText("Unavailable",{exact:true}).first().waitFor();
    assert.match(await page.locator("main").innerText(),/unavailable/i);
  });
  assert.deepEqual(errors,[],"No browser runtime errors");
} catch(error) { await page.screenshot({path:path.join(artifacts,"failure.png"),fullPage:true}).catch(() => {}); console.error("FAILED AT",page.url()); throw error; }
finally { await context.close(); await second.close(); await browser.close(); }
