import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {chromium} from 'playwright';
const base=process.env.SMOKE_BASE_URL||'http://localhost:3100', apiBase=process.env.SMOKE_API_BASE_URL||'http://127.0.0.1:8100';
const artifacts=path.resolve('.browser-results/usability');await mkdir(artifacts,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.SMOKE_CHANNEL?{channel:process.env.SMOKE_CHANNEL}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.setDefaultTimeout(15000);
const errors=[],results=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
async function check(name,action){await action();results.push(name);console.log('PASS '+name);}
async function signIn(target,email){await target.goto(base+'/signin');await target.locator('input[type=email]').fill(email);await target.getByRole('button',{name:'Email me a link'}).click();await target.getByRole('link',{name:'open the link'}).click();await target.waitForURL(base+'/');}
async function bodyIs(value){await page.waitForFunction(expected=>document.querySelector('textarea[aria-label="Your analysis"]')?.value===expected,value);}
async function backend(ctx,route,method='GET',data){const token=(await ctx.cookies()).find(cookie=>cookie.name==='fh_session')?.value;const response=await fetch(apiBase+route,{method,headers:{'X-API-Key':'preview','X-Session':token,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});return{status:response.status,data:await response.json()};}
let projectId,noteId;
try{
await check('Ambiguous company search supports keyboard selection and exact tickers',async()=>{
 await page.goto(base+'/');await page.getByLabel('Search company, ticker or CIK').fill('a');await page.getByRole('option').first().waitFor();assert.ok(await page.getByRole('option').count()>1);await page.getByLabel('Search company, ticker or CIK').press('ArrowDown');await page.getByLabel('Search company, ticker or CIK').press('Enter');await page.waitForURL(/\/companies\/\d+$/);
 await page.goto(base+'/');await page.getByLabel('Search company, ticker or CIK').fill('AAPL');await page.getByRole('option').filter({hasText:'Apple'}).waitFor();await page.getByLabel('Search company, ticker or CIK').press('Enter');await page.waitForURL(base+'/companies/320193');
});
await signIn(page,`usability-owner-${Date.now()}@example.com`);
const project=(await(await context.request.post(base+'/api/projects',{data:{name:'Usability source research'}})).json()).project;projectId=project.id;
const note=(await(await context.request.post(base+`/api/projects/${projectId}/notes`,{data:{title:'Working view',body:'Original saved text',kind:'thesis'}})).json()).note;noteId=note.id;
await check('Unsaved analysis survives navigation, browser Back and reload while exports stay saved-only',async()=>{
 await page.goto(base+`/projects/${projectId}`);await page.getByLabel('Your analysis',{exact:true}).fill('Critical unsaved observation');await page.locator('.draft-recovery-notice').waitFor();
 await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Research',exact:true}).click();await page.waitForURL(base+'/research');await page.goBack();await bodyIs('Critical unsaved observation');await page.reload();await bodyIs('Critical unsaved observation');
 const exported=await(await context.request.get(base+`/api/projects/${projectId}/export`)).json();assert.equal(exported.notes[0].body,'Original saved text');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(artifacts,'after-recovered-draft.png'),fullPage:true});
});
await check('Typing during delayed save remains unsaved and is persisted by the next save',async()=>{
 let release,sent;const gate=new Promise(resolve=>release=resolve),started=new Promise(resolve=>sent=resolve);
 await page.route('**/api/projects/*/notes/*',async route=>{if(route.request().method()==='PATCH'){sent();await gate;}await route.continue();});
 await page.getByLabel('Your analysis',{exact:true}).fill('First save payload');await page.getByRole('button',{name:'Save changes',exact:true}).click();await started;await page.getByLabel('Your analysis',{exact:true}).fill('New writing typed while save was pending');release();await page.getByRole('status').filter({hasText:'newer edits'}).waitFor();await bodyIs('New writing typed while save was pending');
 assert.equal((await(await context.request.get(base+`/api/projects/${projectId}/notes/${noteId}`)).json()).note.body,'First save payload');await page.unroute('**/api/projects/*/notes/*');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved to this project'}).waitFor();await page.reload();await bodyIs('New writing typed while save was pending');assert.equal(await page.locator('.draft-recovery-notice').count(),0);
});
await check('Recovered competing edits require revision comparison and failed saves retain drafts',async()=>{
 await page.getByLabel('Your analysis',{exact:true}).fill('Recovered local contribution');await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Research',exact:true}).click();await page.waitForURL(base+'/research');
 const latest=(await(await context.request.get(base+`/api/projects/${projectId}/notes/${noteId}`)).json()).note;assert.equal((await context.request.patch(base+`/api/projects/${projectId}/notes/${noteId}`,{data:{expected_revision:latest.revision,body:'Concurrent team contribution'}})).status(),200);
 await page.goto(base+`/projects/${projectId}`);await bodyIs('Recovered local contribution');await page.getByRole('button',{name:'Compare latest saved version',exact:true}).click();await page.locator('.note-conflict').getByText('Concurrent team contribution',{exact:true}).waitFor();await page.getByRole('button',{name:'Keep my draft for merging',exact:true}).click();
 await page.route('**/api/projects/*/notes/*',route=>route.request().method()==='PATCH'?route.fulfill({status:503,contentType:'application/json',body:'{"error":"Simulated save outage"}'}):route.continue());await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('alert').filter({hasText:'Simulated save outage'}).waitFor();await bodyIs('Recovered local contribution');await page.unroute('**/api/projects/*/notes/*');await page.getByLabel('Your analysis',{exact:true}).fill('Merged local and team research');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('status').filter({hasText:'Saved to this project'}).waitFor();
});
await check('Search filters survive source inspection, capture comparison, return and clear',async()=>{
 const query=new URLSearchParams({q:'repurchase',cik:'320193',form:'8-K',from:'2020-01-01',to:'2026-12-31',offset:'0'});await page.goto(base+'/research?'+query);await page.getByRole('link',{name:'Read indexed text'}).first().click();await page.getByRole('region',{name:'Extracted filing text'}).waitFor();const version=await page.locator('#before-version option:not([disabled])').first().getAttribute('value');assert.ok(version);await page.getByLabel('Compare this version with').selectOption(version);await page.getByRole('button',{name:'Compare captured text'}).click();await page.getByLabel('Captured text comparison').waitFor();await page.getByRole('link',{name:'Clear comparison'}).click();await page.waitForURL(url=>!url.searchParams.has('before'));
 await page.getByRole('link',{name:'Back to search results',exact:false}).click();await page.locator('.research-results').waitFor();const returned=new URL(page.url());for(const key of ['q','cik','form','from','to'])assert.equal(returned.searchParams.get(key),query.get(key));await page.getByRole('link',{name:'Clear',exact:true}).click();await page.waitForURL(base+'/research');await page.getByRole('heading',{name:'What are you looking for?',exact:true}).waitFor();assert.equal(await page.locator('#site-search').inputValue(),'');
 await page.goto(base+'/research?q=disclosurepaginationfixture');
 // Navigation may finish while Next is still showing the streamed loading boundary.
 // Wait for the actual results, then verify both pages rather than sampling the loading DOM.
 await page.getByRole('heading',{name:'25 documents found',exact:true}).waitFor();
 const pager=page.getByRole('navigation',{name:'Search result pages'}),next=pager.getByRole('link',{name:'Next →',exact:true});await next.waitFor();
 assert.equal(await next.count(),1,'Fixture query has enough documents for actual pagination');assert.equal(await page.locator('.research-results > li').count(),20);
 const firstPageSources=await page.locator('.research-results h2 a').evaluateAll(links=>links.map(link=>new URL(link.href).pathname));
 await next.focus();await next.press('Enter');await page.waitForURL(url=>Number(url.searchParams.get('offset'))===20);assert.equal(new URL(page.url()).searchParams.get('q'),'disclosurepaginationfixture');
 await pager.getByText('Page 2',{exact:true}).waitFor();assert.equal(await page.locator('.research-results > li').count(),5);assert.equal(await next.count(),0);
 const secondPageSources=await page.locator('.research-results h2 a').evaluateAll(links=>links.map(link=>new URL(link.href).pathname));assert.equal(new Set([...firstPageSources,...secondPageSources]).size,25,'Pagination returns every fixture document exactly once');
 const previous=pager.getByRole('link',{name:'← Previous',exact:true});await previous.focus();await previous.press('Enter');await page.waitForURL(url=>!url.searchParams.has('offset'));await pager.getByText('Page 1',{exact:true}).waitFor();assert.equal(await page.locator('.research-results > li').count(),20);
});
await check('Custom counts and comparative choices remain explicit through modes, cutoff and export',async()=>{
 await page.goto(base+'/companies/320193/statements?periods=FY2025&mode=annual');assert.equal(await page.getByLabel('Number of periods').inputValue(),'1');assert.equal(await page.getByLabel('Number of periods').isDisabled(),true);await page.getByRole('link',{name:'All periods',exact:true}).click();await page.waitForURL(url=>!url.searchParams.has('periods'));
 await page.goto(base+'/companies/320193/statements?limit=1&mode=annual');assert.equal(await page.getByLabel('Number of periods').inputValue(),'1');assert.equal(await page.locator('.stmt thead .num').count(),1);await page.getByRole('button',{name:/Display options/}).click();await page.locator('#statement-display-options').getByLabel('latest-filed comparatives',{exact:true}).click();await page.waitForURL(url=>url.searchParams.get('restated')==='1');
 await page.goto(base+'/companies/320193/statements?mode=annual&restated=0&limit=4');await page.getByLabel('Number of periods').selectOption('6');await page.waitForURL(url=>url.searchParams.get('limit')==='6');assert.equal(new URL(page.url()).searchParams.get('restated'),'0');await page.getByRole('button',{name:/Display options/}).click();assert.equal(await page.locator('#statement-display-options').getByLabel('latest-filed comparatives',{exact:true}).isChecked(),false);await page.getByLabel('Filings available by',{exact:true}).fill('2024-12-31');await page.getByRole('button',{name:'Apply cutoff',exact:true}).click();await page.waitForURL(url=>url.searchParams.get('as_of')==='2024-12-31');
 for(const mode of ['quarterly','ltm','annual']){await page.getByRole('combobox',{name:'Periods',exact:true}).selectOption(mode);await page.waitForURL(url=>url.searchParams.get('mode')===mode);assert.equal(new URL(page.url()).searchParams.get('as_of'),'2024-12-31');}
 await page.getByRole('button',{name:/Export to Excel/}).click();const dialog=page.getByRole('dialog',{name:'Export to Excel'});assert.equal(await dialog.getByLabel('latest-filed comparatives',{exact:true}).isChecked(),false);await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(artifacts,'after-period-controls.png'),fullPage:true});
});
await check('Team editing persists and removed members cannot reopen locally cached drafts',async()=>{
 const memberContext=await browser.newContext(),memberPage=await memberContext.newPage();memberPage.on('dialog',dialog=>dialog.accept());await signIn(memberPage,`usability-member-${Date.now()}@example.com`);const member=(await backend(memberContext,'/me')).data.user, organization=(await backend(context,'/organizations','POST',{name:'Usability isolated team'})).data.organization;assert.equal((await backend(context,`/organizations/${organization.id}/members`,'POST',{user_id:member.id,role:'member'})).status,201);
 const teamProject=(await(await context.request.post(base+'/api/projects',{data:{name:'Team research',organization_id:organization.id,template_id:'company-overview'}})).json()).project;await memberPage.goto(base+`/projects/${teamProject.id}`);await memberPage.getByLabel('Your analysis',{exact:true}).fill('Member research contribution');assert.equal(await memberPage.getByRole('button',{name:'Delete note',exact:true}).count(),0);await memberPage.getByRole('button',{name:'Save changes',exact:true}).click();await memberPage.getByRole('status').filter({hasText:'Saved to this project'}).waitFor();const ownerExport=await(await context.request.get(base+`/api/projects/${teamProject.id}/export`)).json();assert.ok(ownerExport.notes.some(item=>item.body==='Member research contribution'));
 await memberPage.getByLabel('Your analysis',{exact:true}).fill('Unsaved after last authorized edit');await memberPage.locator('.draft-recovery-notice').waitFor();assert.equal((await backend(context,`/organizations/${organization.id}/members/${member.id}`,'DELETE')).status,200);await memberPage.reload();await memberPage.getByRole('heading',{name:'Let’s find the right company.',exact:true}).waitFor();assert.equal(await memberPage.getByRole('textbox',{name:'Your analysis',exact:true}).count(),0);assert.ok(!(await memberPage.locator('main').innerText()).includes('Unsaved after last authorized edit'));assert.equal((await memberContext.request.get(base+`/api/projects/${teamProject.id}/export`)).status(),404);await memberContext.close();
});
await check('Mobile keyboard editing retains layout and an explicit recoverable draft',async()=>{
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+`/projects/${projectId}`);await page.getByLabel('Your analysis',{exact:true}).fill('Mobile draft for the next session');await page.getByLabel('Your analysis',{exact:true}).press('Tab');await page.locator('.draft-recovery-notice').waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(artifacts,'after-mobile-editor.png'),fullPage:true});await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Research',exact:true}).click();await page.waitForURL(base+'/research');await page.goBack();await bodyIs('Mobile draft for the next session');
});
assert.deepEqual(errors,[]);await writeFile(path.join(artifacts,'acceptance.json'),JSON.stringify({passed:results.length,scenarios:results,runtimeErrors:errors},null,2));
}catch(error){await page.screenshot({path:path.join(artifacts,'failure.png'),fullPage:true}).catch(()=>{});console.error('FAILED AT',page.url());throw error;}finally{await browser.close();}
