import Link from "next/link";
import EarlyAccessForm from "@/components/EarlyAccessForm";
import { currentUser } from "@/lib/session";
import { workspaceRequest } from "@/lib/workspace-api";
import type { Campaign } from "@/lib/launch-types";
import styles from "@/components/Marketing.module.css";
export const dynamic="force-dynamic";
export const metadata={title:"Founding members · Six months from launch"};
export default async function Page(){const [user,result]=await Promise.all([currentUser(),workspaceRequest<{campaign:Campaign}>("/launch/campaign")]);const campaign=result.data?.campaign;return <div className={styles.page}><div className={styles.formGrid}><div className={styles.hero}><p className="eyebrow">The founding group</p><h1>Be part of the first chapter.</h1><p>Disclosure opens 1 November 2026. Our first twenty founding members receive six months of the launch plan, free.</p><dl className={styles.facts}><div><dt>The group</dt><dd>20 individual accounts</dd></div><div><dt>Your access</dt><dd>1 November 2026 – 30 April 2027</dd></div><div><dt>At the end</dt><dd>No automatic charge</dd></div><div><dt>Current availability</dt><dd>{!campaign?"Could not be confirmed":campaign.state==="closed"?"Reservations have closed":campaign.state==="full"?"Full · waiting list open":`${campaign.remaining} of ${campaign.capacity} places available`}</dd></div></dl><p className={styles.note}>Reservations close at launch. Availability is checked when you confirm; an unfinished signup does not hold a place.</p></div><div className={styles.formCard}><EarlyAccessForm signedIn={!!user} campaign={campaign??null}/></div></div>
    <section className={styles.terms} id="offer-terms"><p className="eyebrow">The offer, clearly stated</p><h2>Room to make it your own.</h2><ol><li>Reserve before 1 November 2026 with a verified Disclosure account and explicitly accept this offer. The first twenty qualifying accounts are allocated a place in confirmation order.</li><li>The offer is for one individual account per person. It does not include an organisation-wide subscription. All regions share the same twenty places.</li><li>Free launch-plan access begins 1 November 2026 and ends at the start of 1 May 2027. Joining early does not start the six-month clock early.</li><li>The launch plan includes available company filings and text search, financial statements and Excel exports, ownership views, watchlists, personal projects and preferences. Source coverage and supported calculations vary by company and period.</li><li>Optional AI is subject to configured availability and usage limits; unlimited AI and third-party premium research are not included. Available service limits apply independently of this offer.</li><li>No card is needed to reserve. There is no automatic charge or automatic paid renewal at the end. Any later paid plan requires a separate choice.</li><li>Once the places are filled, you can join the waiting list before reservations close. A waiting-list position is not a free subscription and does not guarantee a place.</li></ol><p><Link href="/coverage">Check coverage</Link> · <Link href="/privacy">How your information is handled</Link> · <Link href="/company/contact">Ask about the offer</Link></p></section>
  </div>;}
