import Link from "next/link";
import styles from "@/components/Marketing.module.css";
export const metadata={title:"Research resources"};
const faqs=[
  ["Which markets are covered?","Start with public SEC company disclosures. Availability varies by company, period and document type. The live coverage page describes the indexed material; selecting a login region does not add market coverage."],
  ["Can I trace a number back to its filing?","Select a supported financial value to inspect its reported inputs, source filing and calculation, if one is used. An exact table or page location is shown only when available."],
  ["Can I use the numbers in Excel?","Yes. Select your statement, periods and display choices, then open the export dialog. Check currency, scale and whether you are using as-filed values or latest-filed comparatives before downloading."],
  ["Are all shareholders included?","No. Insider, institutional and beneficial ownership filings serve different purposes and only reveal part of the ownership picture. Their dates, reporting thresholds and scope differ."],
  ["Is regional login a data-hosting choice?","All regions currently use Disclosure Global. The selected region is a preference; it does not move your data, create a regional workspace or change filing coverage."],
  ["What does the founding-member offer include?","The first twenty verified individual accounts that explicitly reserve before launch receive the launch plan from 1 November 2026 through 30 April 2027. AI is subject to configured availability and usage limits. Read the offer page for the complete terms and current availability."],
];
export default function Page(){return <div className={styles.page}><div className={styles.hero}><p className="eyebrow">Resources</p><h1>A clearer way into the work.</h1><p>Practical guides to the research tools, the reported figures and the limits of the available sources.</p></div><nav className={styles.jump} aria-label="Resource topics">{[["getting-started","Getting started"],["guides","Research guides"],["methodology","Methodology"],["updates","Product updates"],["faq","FAQs"]].map(([id,title])=><a key={id} href={`#${id}`}>{title}</a>)}</nav>
    <section className={styles.section} id="getting-started"><div><p className={styles.number}>01 / START HERE</p><h2>Your first company research session.</h2><p>A short path from a company name to a saved observation.</p></div><div><ol className={styles.steps}><li>Search by ticker, name or CIK and confirm the company.</li><li>Choose a reporting period and open its related filings.</li><li>Select a financial value and inspect the underlying evidence.</li><li>Write down your interpretation in a project, then attach the source.</li></ol><Link href="/companies/320193" className="text-link">Try the company workflow →</Link></div></section>
    <section className={styles.section} id="guides"><div><p className={styles.number}>02 / RESEARCH GUIDES</p><h2>Ask more precise questions.</h2><p>Use search to locate relevant language, then read it in context.</p></div><div><div className={styles.example}><strong>Search a phrase and a risk</strong><p>Try <code>"supply chain" AND risk</code>. Add a company and filing-date range to narrow the source set. Use the original document to check the surrounding discussion.</p></div><div className={styles.example}><strong>Export a consistent selection</strong><p>Choose annual or quarterly periods, set the scale, check the restatement choice and use the export dialog. Per-share amounts and share counts retain their own units.</p></div><Link href="/research" className="text-link">Open filing search →</Link></div></section>
    <section className={styles.section} id="methodology"><div><p className={styles.number}>03 / METHODOLOGY</p><h2>Keep the source in the picture.</h2><p>A figure becomes useful when you understand what it measures, when it was reported and where it came from.</p></div><div><ol className={styles.steps}><li>Financial statements retain source context. Supported calculated values identify their inputs and formula.</li><li>As-filed values and later-filed comparatives are separate options. A filing-date cutoff answers a different question from a financial period selection.</li><li>Search results describe the indexed documents. Missing results do not establish that the company has never discussed a topic.</li><li>Cited research links to exact indexed passages. A matching citation establishes its location; you still assess whether it supports the conclusion.</li></ol><Link href="/coverage" className="text-link">Inspect coverage and sources →</Link></div></section>
    <section className={styles.section} id="updates"><div><p className={styles.number}>04 / PRODUCT UPDATES</p><h2>Taking shape, thoughtfully.</h2><p>September 2026 · Preparing for our 1 November opening.</p></div><div><p>The current interface brings together source-linked financial statements, separate ownership views, cited research, saved projects and account preferences. Our final visual identity uses EB Garamond, Albert Sans, ivory and royal blue.</p><p>Production source availability, email delivery and AI configuration are verified separately from interface development. Check coverage before relying on a workflow.</p><Link href="/early-access" className="text-link">Meet the founding-member offer →</Link></div></section>
    <section id="faq" className={styles.terms}><p className="eyebrow">FAQs</p><h2>A few things to know.</h2>{faqs.map(([q,a])=><details className={styles.faq} key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
  </div>;}
