import MarketingPage, { type MarketingSection } from "@/components/MarketingPage";
export const metadata = { title:"The platform" };
const sections:MarketingSection[] = [
  {id:"filings",title:"Filings, in context.",description:"Find a company’s disclosures and keep the related reporting documents together.",steps:["Search by company, ticker or CIK and choose a reporting period.","Open annual and quarterly reports, earnings releases and available filing exhibits.","Search indexed filing text and return to the original document when you need the full context."],example:"Start with an earnings release, then open the associated annual report to investigate the accounting behind the headline.",note:"Coverage depends on the documents indexed for each company. Original document formatting is preserved in the filing reader.",href:"/research",action:"Search filings"},
  {id:"financials",title:"Financials you can trace.",description:"Read statements across selected periods and carry the figures into your own analysis.",steps:["Choose income statement, balance sheet or cash flow, then select periods and scale.","Select a figure to inspect its reported inputs, source filing and any supported calculation.","Export the selected view to Excel, keeping period choices explicit."],example:"Compare annual sales across available periods, inspect the evidence for a change, then export the same selection.",note:"As-filed values and latest-filed comparatives are distinct choices. Missing values remain visibly unavailable; currencies and units stay explicit.",href:"/companies/320193/statements",action:"Explore financial statements"},
  {id:"ownership",title:"Know who reported what.",description:"Distinguish company insiders, institutional managers and major beneficial owners.",steps:["Read insider cards with the reported name, company role, transaction and source.","Inspect institutional reported positions separately from insider activity.","Open beneficial ownership disclosures and available supporting documents."],example:"Investigate an officer’s transaction without mixing it with a fund manager’s quarterly holdings report.",note:"These filings do not identify every shareholder. Institutional reports have reporting lags; compatible history appears only when available.",href:"/companies/320193/ownership",action:"Explore ownership"},
  {id:"research",title:"Research with evidence beside it.",description:"Ask source-scoped questions and inspect the indexed passages used in the response.",steps:["Choose the companies or indexed documents you want to investigate.","Read the answer alongside exact source passages and their document versions.","Save the research and supported calculations to a project for later review."],example:"Ask what the selected filings say about a business risk, then read the cited passage in the document before using the conclusion.",note:"AI requires a configured provider and available usage allowance. Unsupported questions and unavailable sources are shown explicitly; citations still need your review.",href:"/research/ask",action:"Open cited research"},
  {id:"watchlists",title:"Keep your companies close.",description:"Bring new filings and supported ownership updates into one morning view.",steps:["Follow the companies you research from their company pages.","Review the watchlist’s recent disclosures and separate ownership feeds.","Choose available email-alert options on your verified account."],example:"Start the day with your followed companies and open the new documents that deserve attention.",note:"Delivery depends on the active ingestion schedule and configured email service. This is not an intraday ownership feed.",href:"/watchlist",action:"Open your watchlist"},
  {id:"projects",title:"Keep the thread of your thinking.",description:"Organise observations, working theses and source references in a research project.",steps:["Create a personal project or an authorised organisation project.","Write notes and attach the documents behind them; review competing edits before saving.","Download saved research as portable JSON, including notes and source references."],example:"Keep the supporting evidence and the questions that could change your view beside your working thesis.",note:"Project downloads contain saved writing and references. Original source documents are linked rather than bundled.",href:"/projects",action:"Open projects"},
  {id:"comparison",title:"Compare with the context intact.",description:"Bring supported financial concepts across companies into a shared view.",steps:["Choose the companies and periods relevant to your comparison.","Inspect the units, reporting dates and source context for each available number.","Investigate differences in definitions before drawing a conclusion."],example:"Use the comparison view to identify questions for deeper statement and filing research.",note:"A common label does not guarantee identical accounting treatment. Unsupported concepts remain unavailable.",href:"/compare",action:"Compare companies"},
];
export default function Page(){return <MarketingPage eyebrow="Platform" title="The evidence. The numbers. Your perspective." intro="Disclosure brings company filings, financial statements and research together, with a direct route back to the source." sections={sections}/>;}
