import MarketingPage, { type MarketingSection } from "@/components/MarketingPage";
export const metadata={title:"Research workflows"};
const sections:MarketingSection[]=[
  {id:"earnings",title:"Prepare for earnings.",description:"Build a view of the last reporting period before the next release arrives.",steps:["Open the latest available results and compare prior reporting periods.","Search the filings for the operating questions you want to revisit.","Save your expectations, evidence and follow-up questions in a project."],example:"Keep the release, statements and your working questions together for a company you follow.",href:"/watchlist",action:"Start with your companies"},
  {id:"due-diligence",title:"Understand a new company.",description:"Work from the company’s disclosures towards your own assessment.",steps:["Check coverage and identify the reports available for the company.","Read the business, risk and financial disclosures; follow relevant filing exhibits.","Record the evidence, open questions and counterarguments in a research project."],note:"Public filings are one part of due diligence. Disclosure does not establish that every relevant document or risk has been identified.",href:"/research",action:"Find company disclosures"},
  {id:"comparison",title:"Investigate the differences.",description:"Compare reported financial performance without losing sight of definitions and dates.",steps:["Choose peers and inspect the available reporting periods.","Compare supported figures with units and original sources visible.","Export statements for the adjustments and modelling you perform yourself."],example:"Use a difference in reported margins as a starting point for accounting and business-model questions.",href:"/compare",action:"Open company comparison"},
  {id:"ownership",title:"Follow ownership disclosures.",description:"Read reported changes with the person, role and disclosure type in view.",steps:["Review insider transactions with the filer’s reported position in the company.","Keep institutional holdings and beneficial ownership events separate.","Inspect the source filing and footnotes before interpreting the signal."],note:"A reported transaction alone does not establish the person’s motivation. Holdings coverage and publication delays vary by filing type.",href:"/companies/320193/ownership",action:"Inspect an ownership example"},
  {id:"portfolio",title:"Monitor your research universe.",description:"Give each company you follow a clear route back into your daily workflow.",steps:["Build a watchlist from the company pages.","Review recent indexed disclosures and available ownership events.","Update your saved research when new evidence changes your view."],note:"This workflow monitors disclosures. It is not a live portfolio valuation or trading system.",href:"/watchlist",action:"Build your watchlist"},
  {id:"team-research",title:"Keep a shared research record.",description:"Make the reasoning and its source references easier for authorised colleagues to revisit.",steps:["Create a project in your organisation and check membership access.","Save notes, working theses and research with source references.","Review revision conflicts before merging changes, then download the saved record when needed."],example:"A colleague can follow the evidence behind a note instead of starting the document search again.",href:"/projects",action:"Explore research projects"},
];
export default function Page(){return <MarketingPage eyebrow="Solutions" title="Built around the way you research." intro="From the first look at a company to the next earnings release, connect the work to the documents and figures behind it." sections={sections}/>;}
